In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
RANDOM_SEED=113
np.random.seed(RANDOM_SEED)

In [3]:
data_path = '/kaggle/input/titanic'
train_csv = pd.read_csv(data_path + '/train.csv')
df = pd.DataFrame(train_csv)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [5]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [6]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
df = df.drop(['Cabin', 'Name', 'Ticket', 'Embarked', 'SibSp', 'Parch'], axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   Fare         891 non-null    float64
dtypes: float64(2), int64(3), object(1)
memory usage: 41.9+ KB


In [8]:
df_ = df.dropna(axis=0, how='any')
df_.info()

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  714 non-null    int64  
 1   Survived     714 non-null    int64  
 2   Pclass       714 non-null    int64  
 3   Sex          714 non-null    object 
 4   Age          714 non-null    float64
 5   Fare         714 non-null    float64
dtypes: float64(2), int64(3), object(1)
memory usage: 39.0+ KB


In [9]:
print('Rows removed =', len(df) - len(df_))

Rows removed = 177


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
df_.head()

PassengerId  Survived  Pclass     Sex   Age     Fare
0            1         0       3    male  22.0   7.2500
1            2         1       1  female  38.0  71.2833
2            3         1       3  female  26.0   7.9250
3            4         1       1  female  35.0  53.1000
4            5         0       3    male  35.0   8.0500

In [12]:
df_['Sex'] = le.fit_transform(df_['Sex'])
df_.head()

PassengerId  Survived  Pclass  Sex   Age     Fare
0            1         0       3    1  22.0   7.2500
1            2         1       1    0  38.0  71.2833
2            3         1       3    0  26.0   7.9250
3            4         1       1    0  35.0  53.1000
4            5         0       3    1  35.0   8.0500

In [13]:
X = df_.drop(['Survived', 'PassengerId'], axis=1)
X.head()

Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    0  38.0  71.2833
2       3    0  26.0   7.9250
3       1    0  35.0  53.1000
4       3    1  35.0   8.0500

In [14]:
X = X.values
X

array([[ 3.    ,  1.    , 22.    ,  7.25  ],
       [ 1.    ,  0.    , 38.    , 71.2833],
       [ 3.    ,  0.    , 26.    ,  7.925 ],
       ...,
       [ 1.    ,  0.    , 19.    , 30.    ],
       [ 1.    ,  1.    , 26.    , 30.    ],
       [ 3.    ,  1.    , 32.    ,  7.75  ]])

In [15]:
y = df_['Survived'].values
y[:5]

array([0, 1, 1, 1, 0])

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[ 0.91123237,  0.75905134, -0.53037664, -0.51897787],
       [-1.47636364, -1.31743394,  0.57183099,  0.69189675],
       [ 0.91123237, -1.31743394, -0.25482473, -0.50621356],
       ...,
       [-1.47636364, -1.31743394, -0.73704057, -0.08877362],
       [-1.47636364,  0.75905134, -0.25482473, -0.08877362],
       [ 0.91123237,  0.75905134,  0.15850313, -0.50952283]])

In [17]:
X.shape

(714, 4)

In [18]:
y.shape

(714,)

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(571, 4) (143, 4) (571,) (143,)


In [20]:
import tensorflow as tf
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))
print(tf.__version__)

Num GPUs Available: 0
2.16.1


In [21]:
from tensorflow.keras.models import Sequential
from keras.layers import Dense, Dropout

In [22]:
X_units = X.shape[1]
X_units

4

In [23]:
model=Sequential()
# Input layer
model.add(Dense(units=64, activation='relu', kernel_initializer='random_uniform', input_dim=X_units))
model.add(Dropout(0.5))

# Hidden layer 1
model.add(Dense(units=32, activation='relu', kernel_initializer='random_uniform'))
model.add(Dropout(0.5))

# Hidden layer 2
model.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))

# Output layer
model.add(Dense(units=1, activation='sigmoid', kernel_initializer='random_uniform'))

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
from tensorflow.keras.callbacks import ModelCheckpoint

checkpoint_filepath = '/kaggle/working/titanic-1.weights.h5'

model_checkpoint_callback = ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_weights_only=True,
    monitor='accuracy',
    mode='max',
    save_best_only=True
)

In [26]:
history = model.fit(
    X_train, y_train, 
    epochs=300,
    callbacks=[model_checkpoint_callback]
)

Epoch 1/300
18/18 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.5737 - loss: 0.6926
Epoch 2/300
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5901 - loss: 0.6901 
Epoch 3/300
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5928 - loss: 0.6825 
Epoch 4/300
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7106 - loss: 0.6532 
Epoch 5/300
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7683 - loss: 0.5711 
Epoch 6/300
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8049 - loss: 0.4848 
Epoch 7/300
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8005 - loss: 0.4609 
Epoch 8/300
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7645 - loss: 0.4753 
Epoch 9/300
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7775 - loss: 0.4831 
Epoch 10/300
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7809 - loss: 0.4854 
Epoch 11/300
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7999 - loss: 0.4565 
Epoch 12/300
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step -

In [27]:
model.load_weights(checkpoint_filepath)

In [28]:
y_pred = model.predict(X_test)
print(y_pred.shape)
print(y_pred[:5])

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
(143, 1)
[[0.52076036]
 [0.9871853 ]
 [0.91196823]
 [0.08093856]
 [0.38664204]]


In [29]:
print(y_test.shape)
print(y_test[:5])

(143,)
[0 0 1 0 1]


In [30]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

y_pred_binary = (y_pred > 0.4).astype(int)
y_pred_binary[:5]

array([[1],
       [1],
       [1],
       [0],
       [0]])

In [31]:
# Accuracy
accuracy = accuracy_score(y_test, y_pred_binary)
print(f'Accuracy: {accuracy:.4f}')

# Precision, Recall, F1-score
precision = precision_score(y_test, y_pred_binary)
recall = recall_score(y_test, y_pred_binary)
f1 = f1_score(y_test, y_pred_binary)

print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')
print(f'F1 Score: {f1:.4f}')

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_binary)
print(f'Confusion Matrix:\n{cm}')

Accuracy: 0.8182
Precision: 0.8276
Recall: 0.7500
F1 Score: 0.7869
Confusion Matrix:
[[69 10]
 [16 48]]
